export const scopes = [
  "atproto",
  "rpc:app.bsky.actor.getProfile?aud=*",
  "rpc:app.bsky.feed.getTimeline?aud=*",
  "rpc:app.bsky.feed.getAuthorFeed?aud=*",
  "rpc:app.bsky.feed.getPostThread?aud=*",
  "rpc:app.bsky.feed.getActorLikes?aud=*",
  "rpc:app.bsky.bookmark.getBookmarks?aud=*",
  "rpc:app.bsky.bookmark.createBookmark?aud=*",
  "rpc:app.bsky.bookmark.deleteBookmark?aud=*",
  "rpc:app.bsky.notification.listNotifications?aud=*",
  "rpc:app.bsky.notification.getUnreadCount?aud=*",
  "rpc:app.bsky.notification.updateSeen?aud=*",
  "repo:*",
  "blob:*/*",
];
