name: Code Check

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  oxlint:
    runs-on: ubuntu-latest
    steps:
      - run: npm install --global pnpm@latest
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run oxlint

  oxfmt:
    runs-on: ubuntu-latest
    steps:
      - run: npm install --global pnpm@latest
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run oxfmt

  depcruise:
    runs-on: ubuntu-latest
    steps:
      - run: npm install --global pnpm@latest
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run depcruise

  steiger:
    runs-on: ubuntu-latest
    steps:
      - run: npm install --global pnpm@latest
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run steiger

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - run: npm install --global pnpm@latest
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - run: npm install --global pnpm@latest
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm exec playwright install --with-deps chromium
      - run: pnpm run test
