name: Quality Gate

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  oxlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v1
        with:
          cache: true
      - run: pnpm run oxlint

  oxfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v1
        with:
          cache: true
      - run: pnpm run oxfmt

  depcruise:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v1
        with:
          cache: true
      - run: pnpm run depcruise

  steiger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v1
        with:
          cache: true
      - run: pnpm run steiger

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v1
        with:
          cache: true
      - run: pnpm run typecheck

  get-playwright-version:
    runs-on: ubuntu-latest
    outputs:
      PLAYWRIGHT_VERSION: ${{ steps.get-playwright-version.outputs.PLAYWRIGHT_VERSION }}
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v1
        with:
          cache: true
      - id: get-playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(pnpm exec playwright --version | cut -d ' ' -f 2)" >> $GITHUB_OUTPUT

  vitest:
    runs-on: ubuntu-latest
    needs:
      - get-playwright-version
    container:
      image: mcr.microsoft.com/playwright:v${{ needs.get-playwright-version.outputs.PLAYWRIGHT_VERSION }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v1
        with:
          cache: true
      - run: pnpm run vitest
      - uses: davelosert/vitest-coverage-report-action@v2
        if: always()

  playwright:
    runs-on: ubuntu-latest
    needs:
      - get-playwright-version
    container:
      image: mcr.microsoft.com/playwright:v${{ needs.get-playwright-version.outputs.PLAYWRIGHT_VERSION }}
      options: --user pwuser
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v1
        with:
          cache: true
      - run: pnpm run playwright
      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
